### ISSUE TITLE
can add support for livescript-transform-esm ?

### ISSUE THREAD

**Issue by zsp042** [borestad/vue-livescript-loader#1]
https://github.com/bartosz-m/livescript-transform-esm

**Comment by zsp042** [comment]
i write
https://www.npmjs.com/package/6du-livescript-loader
https://www.npmjs.com/package/vue-cli-plugin-livescript
fixed

**Comment by anhnhoktvn** [comment]
@TqLj How to add `livescript-transform-esm` to your loader?
